app:
  host: localhost
  port: 10101
  auth_key: token
  auth_secret: gin_temp
  auth_expire: 600 # 60 * 10

database:
  host: localhost
  port: 3306
  user: tms
  password: TMSmysql
  table: gin-temp
  charset: utf8mb4
  parse_time: true
  loc: Local

  prefix: tb_
  singular_table: true

redis:
  host: localhost
  port: 6379
  password: redis
  db: 0

logger:
  dir: ./logs

file:
  dir: /home/tms/Desktop/temp/TMS-GIN-FILE
  max_size: 10 # MB
