package constant

var MimeTypes = map[string]string{
	".html":    "text/html",
	".css":     "text/css",
	".js":      "application/javascript",
	".json":    "application/json",
	".xml":     "application/xml",
	".pdf":     "application/pdf",
	".txt":     "text/plain",
	".jpg":     "image/jpeg",
	".jpeg":    "image/jpeg",
	".png":     "image/png",
	".gif":     "image/gif",
	".svg":     "image/svg+xml",
	".ico":     "image/vnd.microsoft.icon",
	".mp3":     "audio/mpeg",
	".wav":     "audio/wav",
	".mp4":     "video/mp4",
	".avi":     "video/x-msvideo",
	".zip":     "application/zip",
	".tar":     "application/x-tar",
	".gz":      "application/gzip",
	".tar.gz":  "application/x-gzip",
	".tar.bz2": "application/x-bzip2",
	".doc":     "application/msword",
	".docx":    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".xls":     "application/vnd.ms-excel",
	".xlsx":    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".ppt":     "application/vnd.ms-powerpoint",
	".pptx":    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	// 添加更多...
}
